export enum UserRole {
  SUPERADMIN = "SUPERADMIN",
  SUPERVISOR = "SUPERVISOR",
  ADMIN = "ADMIN",
  STAFF = "STAFF",
  WAREHOUSE = "WAREHOUSE",
  PURCHASER = "PURCHASER",
  FINANCER = "FINANCER",
  AUTHORIZER = "AUTHORIZER",
  ACCOUNTANT = "ACCOUNTANT",
}
