/** يطابق `enum Role` في `schema.prisma` */
export enum UserRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  GARAGE_OWNER = "GARAGE_OWNER",
  DRIVER = "DRIVER",
  USER = "USER",
  TOURISM_OWNER = "TOURISM_OWNER",
  HOTEL_OWNER = "HOTEL_OWNER",
  RESTAURANT_OWNER = "RESTAURANT_OWNER",
  FARM_OWNER = "FARM_OWNER",
}
