import type { Metadata } from "next";
import "../app/globals.css";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "next-themes";
import { auth } from "@/auth";
import dynamic from "next/dynamic";
import { Cairo } from "next/font/google";

const ToastProvider = dynamic(
  () => import("@/components/Shared/ToastProvider"),
  { ssr: false }
);

const cairo = Cairo({
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
  variable: "--font-cairo",
});
export const metadata: Metadata = {
  title: "MANAGE-Instituion | Home",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en" dir="rtl">
        <body className={`${cairo.variable} ${cairo.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div>{children}</div>
            <ToastProvider />
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
