import type { Metadata } from "next";
import "./globals.css";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
import { ThemeProvider } from "next-themes";
import { auth } from "@/auth";
import dynamic from "next/dynamic";
import { Cairo } from "next/font/google";

const ToastProvider = dynamic(
  () => import("@/components/Shared/ToastProvider"),
  { ssr: false }
);

const cairo = Cairo({
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
  variable: "--font-cairo",
  preload: true,
  fallback: ["system-ui", "Segoe UI", "Tahoma", "Arial", "sans-serif"],
});
export const metadata: Metadata = {
  title: "MANAGE-Instituion | Home",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning className={cairo.variable}>
      <body className={`${cairo.className} min-h-screen bg-background font-sans antialiased`}>
        <SessionProviderWrapper session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div>{children}</div>
            <ToastProvider />
          </ThemeProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
